export const OPEN_CIRCLE_NAV = 'OPEN_CIRCLE_NAV'
export const CLOSE_CIRCLE_NAV = 'CLOSE_CIRCLE_NAV'
export const SHOW_PARTICLES = 'SHOW_PARTICLES'
export const HIDE_PARTICLES = 'HIDE_PARTICLES'

export const OPEN_HOME_SCREEN = 'OPEN_HOME_SCREEN'
export const OPEN_RESUME_SCREEN = 'OPEN_RESUME_SCREEN'
export const OPEN_PROJECTS_SCREEN = 'OPEN_PROJECTS_SCREEN'

export const SHOW_RECOMMENDATIONS_SECTION = 'SHOW_RECOMMENDATIONS_SECTION'
export const SHOW_SUMMARY_SECTION = 'SHOW_SUMMARY_SECTION'
export const SHOW_SKILLS_SECTION = 'SHOW_SKILLS_SECTION'
export const SHOW_EDUCATION_SECTION = 'SHOW_EDUCATION_SECTION'
export const SHOW_EXPERIENCE_SECTION = 'SHOW_EXPERIENCE_SECTION'

export const GET_EDUCATION_DETAILS = 'GET_EDUCATION_DETAILS'
export const SET_LOADING = 'SET_LOADING'

export const GET_PROJECTS_DETAILS = 'GET_PROJECTS_DETAILS'