export const OPEN_CIRCLE_NAV = 'OPEN_CIRCLE_NAV'
export const CLOSE_CIRCLE_NAV = 'CLOSE_CIRCLE_NAV'

export const OPEN_HOME_SCREEN = 'OPEN_HOME_SCREEN'
export const OPEN_RESUME_SCREEN = 'OPEN_RESUME_SCREEN'
export const OPEN_COVER_LETTER_SCREEN = 'OPEN_COVER_LETTER_SCREEN'
export const OPEN_PROJECTS_SCREEN = 'OPEN_PROJECTS_SCREEN'

export const SHOW_RECOMMENDATIONS_SECTION = 'SHOW_RECOMMENDATIONS_SECTION'
export const SHOW_SUMMARY_SECTION = 'SHOW_SUMMARY_SECTION'
export const SHOW_SKILLS_SECTION = 'SHOW_SKILLS_SECTION'
export const SHOW_EDUCATION_SECTION = 'SHOW_EDUCATION_SECTION'
export const SHOW_EXPERIENCE_SECTION = 'SHOW_EXPERIENCE_SECTION'