export const OPEN_CIRCLE_NAV = 'OPEN_CIRCLE_NAV'
export const CLOSE_CIRCLE_NAV = 'CLOSE_CIRCLE_NAV'

export const OPEN_HOME_SCREEN = 'OPEN_HOME_SCREEN'
export const OPEN_RESUME_SCREEN = 'OPEN_RESUME_SCREEN'
export const OPEN_COVER_LETTER_SCREEN = 'OPEN_COVER_LETTER_SCREEN'
export const OPEN_PROJECTS_SCREEN = 'OPEN_PROJECTS_SCREEN'